import type { DiscoverCase, DiscoverCategory } from './discover.types'

export const DISCOVER_CATEGORIES = [
  '全部',
  '精选画布',
  '概念短片',
  '角色设定',
  '商业广告',
  '世界设定',
] as const satisfies readonly DiscoverCategory[]

export const DISCOVER_CASES = [
  {
    id: 'beast',
    featured: true,
    image: '/discover/liblib-showcase/long-video.webp',
    imageAlt: '粉色片场中被举起的电影场记板',
    video: '/discover/liblib-showcase/long-video.webm',
    title: '玄麟 · 雪原追猎',
    description: '从角色设定到电影感动态镜头',
    author: '云舟',
    category: '概念短片',
    likes: '1.8k',
    prompt: '东方玄幻巨兽玄麟在暴风雪原疾驰，电影级动态镜头，冷蓝色光影。',
  },
  {
    id: 'warrior',
    featured: true,
    image: '/discover/liblib-showcase/segment-remake.webp',
    imageAlt: '两名黑衣人物从汽车后备箱上方向下看',
    video: '/discover/liblib-showcase/segment-remake.webm',
    title: '霜华 · 角色统一方案',
    description: '三张参考图完成稳定角色设定',
    author: '林野',
    category: '角色设定',
    likes: '946',
    prompt: '设计一位白衣女侠的完整角色设定，保持正面、侧面和背面造型一致。',
  },
  {
    id: 'watch',
    featured: false,
    image: '/discover/liblib-showcase/smart-continuation.webp',
    imageAlt: '戴护目镜的人物飞越现代城市',
    video: '/discover/liblib-showcase/smart-continuation.webm',
    title: '时间之外',
    description: '奢侈腕表十五秒视觉广告',
    author: 'MONO LAB',
    category: '商业广告',
    likes: '621',
    prompt: '黑色机械腕表悬浮在环形光轨中央，奢侈品广告质感，十五秒视觉短片。',
  },
  {
    id: 'city',
    featured: true,
    image: '/discover/liblib-showcase/video-analysis.webp',
    imageAlt: '蓝绿色背景中的东方古画人物拼贴',
    video: '/discover/liblib-showcase/video-analysis.mp4',
    title: '灯火长安',
    description: '东方幻想城市氛围概念片',
    author: '折光社',
    category: '世界设定',
    likes: '733',
    prompt: '东方幻想古城依山而建，雨雾、灯火和石桥构成深远的城市氛围。',
  },
  {
    id: 'tide',
    featured: true,
    image: '/discover/liblib-showcase/director-guide.webp',
    imageAlt: '聚光灯下悬浮的银白色运动鞋',
    video: '/discover/liblib-showcase/director-guide.webm',
    title: '潮汐之门',
    description: '深海遗迹概念镜头与环境氛围',
    author: '北屿',
    category: '概念短片',
    likes: '524',
    prompt: '探索深海遗迹中的潮汐之门，巨型守护生物从风暴海面冲出。',
  },
  {
    id: 'small-world',
    featured: false,
    image: '/discover/liblib-showcase/multi-reference.webp',
    imageAlt: '粉色更衣室中拿着电话的女孩',
    video: '/discover/liblib-showcase/multi-reference.webm',
    title: '一人的小世界',
    description: '治愈系角色与微缩场景设定',
    author: '原野',
    category: '角色设定',
    likes: '889',
    prompt: '治愈系东方少女生活在微缩山水世界中，完成角色与场景统一设定。',
  },
  {
    id: 'signal',
    featured: true,
    image: '/discover/watch.webp',
    imageAlt: '环形机械空间中的未来产品',
    title: '深空信标',
    description: '未来科技产品视觉实验',
    author: 'VOID LAB',
    category: '商业广告',
    likes: '412',
    prompt: '未来科技产品悬浮在深空信标装置中，精密机械结构与蓝色聚光环绕。',
  },
  {
    id: 'night-walk',
    featured: true,
    image: '/discover/city.webp',
    imageAlt: '雨夜古城石桥上的独行旅人',
    title: '长安夜行',
    description: '东方古城的雨夜镜头设计',
    author: '折光社',
    category: '世界设定',
    likes: '1.2k',
    prompt: '重建长安雨夜古城，旅人站在石桥中央，万家灯火倒映在河面。',
  },
  {
    id: 'mirror',
    featured: false,
    image: '/discover/warrior.webp',
    imageAlt: '同一白衣角色的三个观察角度',
    title: '镜中旅人',
    description: '同一角色的多场景一致性测试',
    author: '林野',
    category: '角色设定',
    likes: '667',
    prompt: '同一位白衣旅人在雪山、竹林和雨夜三种场景中保持形象完全一致。',
  },
  {
    id: 'after-zero',
    featured: false,
    image: '/discover/watch.webp',
    imageAlt: '冷色光影中的黑色机械腕表',
    title: '零点之后',
    description: '机械腕表的动态光影广告',
    author: 'MONO LAB',
    category: '商业广告',
    likes: '395',
    prompt: '午夜零点，机械腕表在冷色光束中缓慢旋转，细节微距商业广告。',
  },
  {
    id: 'myth',
    featured: false,
    image: '/discover/beast.webp',
    imageAlt: '雪浪中苏醒的东方神话巨兽',
    title: '山海异闻',
    description: '东方巨兽的电影化概念预告',
    author: '云舟',
    category: '概念短片',
    likes: '976',
    prompt: '山海经巨兽在冰封雪原苏醒，黑色鳞甲与蓝色电光，电影概念预告。',
  },
  {
    id: 'academy',
    featured: false,
    image: '/discover/city.webp',
    imageAlt: '云雾笼罩的东方古建筑群',
    title: '雾隐书院',
    description: '古建筑群与自然环境世界构建',
    author: '观澜',
    category: '世界设定',
    likes: '458',
    prompt: '云雾山谷中的东方古书院，层叠建筑、溪流和暖色灯火组成完整世界。',
  },
] as const satisfies readonly DiscoverCase[]
